# Generated by Django 5.2.5 on 2025-09-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0002_student_address_student_permit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='available_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentPlanPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('credits_granted', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.lessonplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.student')),
            ],
        ),
    ]
