# Generated by Django 5.2.5 on 2025-09-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lesson_type',
            field=models.CharField(choices=[('beginner', 'Beginner Lesson'), ('intermediate', 'Intermediate Lesson'), ('advanced', 'Advanced Lesson'), ('test_prep', 'Test Preparation')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
    ]
