# Generated by Django 5.2.5 on 2025-09-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0005_appointment_lesson_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='description',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='includes_test',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='drivingschool.lessonplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
