# Generated by Django 5.2.5 on 2025-10-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0007_remove_student_address_student_city_student_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='description',
            field=models.TextField(default='Professional driving instruction package', help_text='Brief description of the package'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display the plan'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this plan is currently available'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='package_type',
            field=models.CharField(choices=[('standard', 'Standard Package'), ('specialized', 'Specialized Package')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name for the plan', max_length=100),
        ),
    ]
