# Generated by Django 5.2.5 on 2025-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0011_alter_appointment_status_instructoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
